### ISSUE TITLE
there is no such prop for hiding and showing the prop [feature request]

### ISSUE THREAD

**Issue by dharmendrashah** [watadarkstar/react-native-typing-animation#22]
i want to add this in my chat application but i didn't see any options for showing and hiding this prop i can do this by our own side but it will be very helpful that it will be the initiated prop option in this modules.

**Comment by ghost** [comment]
Hi @dharmendrashah, this feature will be released soon. What do you say @watadarkstar? I can start working on this right away.

**Comment by watadarkstar** [comment]
@murageden Happy to have you add a prop that lets the user hide the component. Like so:

- **`hide`** _(Bool)_ - When set to `true` it hides the component

If that's what is being asked?

**Comment by ghost** [comment]
Feature request. Sure. I will make a PR as soon as I get on my desk. Thank you @watadarkstar😊

**Comment by watadarkstar** [comment]
@dharmendrashah Do you mean hiding the component? Because you said "hiding this prop" but that doesn't make sense to me.

**Comment by ghost** [comment]
Yeah, obviously he means the whole view/ Component. I understand @dharmendrashah 's limbo. But we want to keep the library as light as possible, that's why we are making just the loader. The functionality for the loader is considered external to the loader. This feature will only be limited to allowing: **make the component shown/hidden**. It won't include things like timing the **showing**/**hiding** states.

**Comment by ghost** [comment]
@watadarkstar, I raised a request for this feature, kindly review and merge. @dharmendrashah this should be fixed after the merge. This issue should be marked as closed now, @watadarkstar.

**Comment by watadarkstar** [comment]
This has been merged in as of PR #25
